<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-E61TQNU" failures="2" tests="2" name="Validating Title in the page" time="22.15" errors="0" timestamp="15 Dec 2019 19:26:20 GMT">
  <testcase classname="Academy.validateTitle" name="validateAppTitle" time="0.864">
    <failure type="java.lang.AssertionError" message="expected [123ИНТЕРНЕТ-МАГАЗИН СПОРТИВНОГО ПИТАНИЯ] but found [ИНТЕРНЕТ-МАГАЗИН СПОРТИВНОГО ПИТАНИЯ]">
      <![CDATA[java.lang.AssertionError: expected [123ИНТЕРНЕТ-МАГАЗИН СПОРТИВНОГО ПИТАНИЯ] but found [ИНТЕРНЕТ-МАГАЗИН СПОРТИВНОГО ПИТАНИЯ]
	at Academy.validateTitle.validateAppTitle(validateTitle.java:44)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- validateAppTitle -->
  <testcase classname="Academy.validateTitle" name="validateAppTitle" time="0.887">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at resources.base.getScreenshot(base.java:76)
	at Academy.listeners.onTestFailure(listeners.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- validateAppTitle -->
</testsuite> <!-- Validating Title in the page -->
