<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E61TQNU" failures="0" tests="1" name="Academy.validateTitle" time="6.662" errors="1" timestamp="15 Dec 2019 19:24:55 GMT">
  <testcase classname="Academy.validateTitle" name="validateAppTitle" time="6.662">
    <error message="expected [123ÈÍÒÅÐÍÅÒ-ÌÀÃÀÇÈÍ ÑÏÎÐÒÈÂÍÎÃÎ ÏÈÒÀÍÈß] but found [ÈÍÒÅÐÍÅÒ-ÌÀÃÀÇÈÍ ÑÏÎÐÒÈÂÍÎÃÎ ÏÈÒÀÍÈß]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [123ÈÍÒÅÐÍÅÒ-ÌÀÃÀÇÈÍ ÑÏÎÐÒÈÂÍÎÃÎ ÏÈÒÀÍÈß] but found [ÈÍÒÅÐÍÅÒ-ÌÀÃÀÇÈÍ ÑÏÎÐÒÈÂÍÎÃÎ ÏÈÒÀÍÈß]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Academy.validateTitle.validateAppTitle(validateTitle.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </error>
  </testcase> <!-- validateAppTitle -->
</testsuite> <!-- Academy.validateTitle -->
